// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace aether_db.Models
{
    public partial class aether_dbContext : DbContext
    {
        public aether_dbContext()
        {
        }

        public aether_dbContext(DbContextOptions<aether_dbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Command> Commands { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceType> DeviceTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(
                    "Data Source=127.0.0.1;Initial Catalog=aether_db;Persist Security Info=True;User ID=sa;Password=SqlServer2019;TrustServerCertificate=true");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Command>(entity =>
            {
                entity.Property(e => e.Timestamp)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.Device)
                    .WithMany(p => p.Commands)
                    .HasForeignKey(d => d.DeviceID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Commands__Device__36B12243");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Commands)
                    .HasForeignKey(d => d.UserID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Commands__UserID__35BCFE0A");
            });

            modelBuilder.Entity<Device>(entity =>
            {
                entity.HasOne(d => d.DeviceTypeNavigation)
                    .WithMany(p => p.Devices)
                    .HasForeignKey(d => d.DeviceType)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Devices__DeviceT__32E0915F");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Devices)
                    .HasForeignKey(d => d.UserID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Devices__UserID__31EC6D26");
            });

            modelBuilder.Entity<UserPreference>(entity =>
            {
                entity.HasKey(e => e.UserID)
                    .HasName("PK__UserPref__1788CCAC3F164D46");

                entity.Property(e => e.UserID).ValueGeneratedNever();

                entity.HasOne(d => d.User)
                    .WithOne(p => p.UserPreference)
                    .HasForeignKey<UserPreference>(d => d.UserID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__UserPrefe__UserI__29572725");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}