// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aether_db.Models
{
    public partial class Device
    {
        public Device()
        {
            Commands = new HashSet<Command>();
        }

        [Key]
        public int DeviceID { get; set; }
        public int UserID { get; set; }
        public int DeviceType { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string DeviceName { get; set; }

        [ForeignKey("DeviceType")]
        [InverseProperty("Devices")]
        public virtual DeviceType DeviceTypeNavigation { get; set; }
        [ForeignKey("UserID")]
        [InverseProperty("Devices")]
        public virtual User User { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<Command> Commands { get; set; }
    }
}